export const PROJECTS = [
  {
    title: "Bookshelf",
    year: 2026,
    role: "Full-stack Developer",
    shortDescription: "An application for managing and organizing books",
    description:
      "A backend application for managing a personal book collection, built to strengthen my backend development skills with Node.js, Express, and PostgreSQL. The project provides RESTful APIs for book management and is designed to evolve with features such as reading summaries, key takeaways, pair reading, and reading streak tracking.",
    liveUrl: null,
    repositoryUrl: null,
    isPrivate: true,
    libraries: [
      "Typescript",
      "Node",
      "Express",
      "PostgreSQL",
      "Dotenv",
      "Cors",
      "Zod",
    ],
  },
  {
    title: "Foodie",
    year: 2024,
    role: "Frontend Developer",
    shortDescription: "Multi-vendor restaurant management system",
    description:
      "Collaborated with the team from product ideation to implementation, helping design and build an all-in-one restaurant management platform that unifies online ordering, dine-in operations, and business administration into a single application with a comprehensive management dashboard.",
    liveUrl: "https://foodie-live-links.netlify.app",
    repositoryUrl: "https://github.com/orgs/Script-Horizon",
    isPrivate: false,
    libraries: [
      "Javascript",
      "Axios",
      "React",
      "Express",
      "Node",
      "TailwindCSS",
      "NextUI",
      "React-Router",
      "Tanstack Query",
      "Firebase",
      "Stripe",
      "Recharts",
      "React-Hook-Form",
      "Date-Fns",
      "React-Hot-Toast",
      "JsonWebToken",
      "Cors",
      "Dotenv",
      "MongoDB",
      "Mongoose",
    ],
  },
  {
    title: "AirCNC",
    year: 2024,
    role: "Full-Stack Developer",
    shortDescription: "A room accommodation platform for travellers",
    description:
      "A full-stack accommodation booking platform where hosts can publish and manage rental listings, while guests can browse available properties, make reservations, and manage their bookings within a date range through an intuitive interface.",
    liveUrl: "https://air-cnc-588ed.web.app",
    repositoryUrl: "https://github.com/farhannilok/AirCNC",
    isPrivate: false,
    libraries: [
      "React",
      "Node",
      "Express",
      "Javascript",
      "JsonWebToken",
      "React Router Dom",
      "TailwindCSS",
      "Firebase",
      "Date-Fns",
      "React-Hot-Toast",
      "React-Icons",
      "MongoDB",
      "Dotenv",
      "Cors",
    ],
  },
  {
    title: "CarDoctor",
    year: 2024,
    role: "Full-Stack Developer",
    shortDescription: "An automobile service website",
    description:
      "A full-stack web application for booking automotive services, enabling users to explore service offerings, manage appointments, and authenticate securely using Firebase Authentication with email/password and Google Sign-In.",
    liveUrl: "https://car-doctor-9c6fe.web.app/",
    repositoryUrl: "https://github.com/farhannilok/car-doctor",
    isPrivate: false,
    libraries: [
      "Javascript",
      "React",
      "TailwindCSS",
      "Node",
      "Express",
      "MongoDB",
      "DaisyUI",
      "JsonWebToken",
      "Firebase",
      "Dotenv",
      "Cors",
    ],
  },
] as const
