export const SKILLS = [
  { name: "JavaScript", ariaLabel: "JavaScript" },
  { name: "TypeScript", ariaLabel: "TypeScript" },
  { name: "React", ariaLabel: "ReactJS" },
  { name: "Tailwind CSS", ariaLabel: "TailwindCSS" },
  { name: "shadcn/ui", ariaLabel: "shadcn/ui" },
  { name: "DaisyUI", ariaLabel: "DaisyUI" },
  { name: "Headless UI", ariaLabel: "HeadlessUI" },
  { name: "Material UI", ariaLabel: "MaterialUI" },
  { name: "NextUI", ariaLabel: "NextUI" },
  { name: "Node.js", ariaLabel: "NodeJS" },
  { name: "Express.js", ariaLabel: "ExpressJS" },
  { name: "PostgreSQL", ariaLabel: "PostgreSQL" },
  { name: "MongoDB", ariaLabel: "MongoDB" },
  { name: "Linux", ariaLabel: "Linux" },
  { name: "Git", ariaLabel: "Git" },
  { name: "GitHub", ariaLabel: "GitHub" },
  { name: "Zustand", ariaLabel: "Zustand" },
  { name: "TanStack Query", ariaLabel: "TanStack Query" },
  { name: "Redux Toolkit", ariaLabel: "Redux Toolkit" },
  { name: "RTK Query", ariaLabel: "RTK Query" },
  { name: "Zod", ariaLabel: "Zod" },
] as const
